% Generated by melete. Edits here are overwritten by the next run.
\version "2.24.0"

\header {
  tagline = ##f
}

\book {
  \bookpart {
    \markup \vspace #3
    \markup \fill-line { \fontsize #6 \bold "Practice session" }
    \markup \vspace #1
    \markup \fill-line { "2026-08-09 — bass6" }
    \markup \vspace #3
    \markup \wordwrap-string #"1. G minor pentatonic, scales, positional, ascending, eighths, range octaves 2, 80-100 bpm"
    \markup \italic \wordwrap-string #"Keep the plucking hand even through the string crossings."
    \markup \vspace #1
    \markup \wordwrap-string #"2. D minor 7th, arpeggios, first inversion, broken, start fret 5, 80-100 bpm"
    \markup \vspace #1
  }

  \bookpart {
    \score {
      \header {
        piece = "1. G minor pentatonic"
      }
      <<
        \new Staff \with {
          \omit StringNumber
        } {
          \clef "bass_8"
          \key g \minor
          \tempo 4 = 80 - 100
          \accidentalStyle forget
          \time 4/4
          g4\2-> bes8\2-3 c'8\2-4 \tuplet 3/2 { d'8\2-1 f'8\2-4 g'8\2-1 } d8\3 b,8\4-2 a,8\4 e,8\5
          b,,4.\6->
          \bar "|."
        }
        \new TabStaff \with {
          stringTunings = \stringTuning <b,, e, a, d g c'>
          \omit Fingering
        } {
          \accidentalStyle forget
          \time 4/4
          g4\2-> ais8\2-3 c'8\2-4 \tuplet 3/2 { d'8\2-1 f'8\2-4 g'8\2-1 } d8\3 b,8\4-2 a,8\4 e,8\5
          b,,4.\6->
          \bar "|."
        }
      >>
      \layout { }
    }

    \score {
      \header {
        piece = "2. D minor 7th"
      }
      <<
        \new Staff \with {
          \omit StringNumber
        } {
          \clef "bass_8"
          \key d \minor
          \tempo 4 = 80 - 100
          \accidentalStyle forget
          \time 4/4
          g4\2-> bes8\2-3 c'8\2-4 \tuplet 3/2 { d'8\2-1 f'8\2-4 g'8\2-1 } d8\3 b,8\4-2 a,8\4 e,8\5
          b,,4.\6->
          \bar "|."
        }
        \new TabStaff \with {
          stringTunings = \stringTuning <b,, e, a, d g c'>
          \omit Fingering
        } {
          \accidentalStyle forget
          \time 4/4
          g4\2-> ais8\2-3 c'8\2-4 \tuplet 3/2 { d'8\2-1 f'8\2-4 g'8\2-1 } d8\3 b,8\4-2 a,8\4 e,8\5
          b,,4.\6->
          \bar "|."
        }
      >>
      \layout { }
    }
  }
}
