% Generated by melete. Edits here are overwritten by the next run.
\version "2.24.0"

\header {
  title = "G minor pentatonic"
  tagline = ##f
}

\score {
  <<
    \new Staff \with {
      \omit StringNumber
    } {
      \clef "bass"
      \key g \minor
      \tempo 4 = 80 - 100
      \accidentalStyle forget
      \time 4/4
      g4\2-> bes8\2-3 c'8\2-4 \tuplet 3/2 { d'8\2-1 f'8\2-4 g'8\2-1 } d8\3 b,8\4-2 a,8\4 e,8\5
      b,,4.\6->
      \bar "|."
    }
  >>
  \layout { }
}
