[project]
repository-type = "application"
versioning-scheme = "semver"
branching-model = "library-release"
release-model = "tagged-release"
primary-language = "python"

[ci]
versions = ["3.14"]
integration-tests = true

[publish]
release = true
docs = false

[dependencies]
vergil = "v2.1"
