r"""Score to LilyPond source text (spec §4, §10, §12).

This module is a pass-through. It receives a `Score` — pitches, string and
fret positions, and **written** durations — and turns it into LilyPond source.
It never learns what a Dorian mode is, and it never learns that a LilyPond
binary exists: `render` is the only module aware of the binary (spec §4), and
nothing here shells out or touches the filesystem.

## Written durations arrive already writable (decision #16)

`Note.duration` is the engraved value and `Tuplet.ratio` supplies the scaling,
so a triplet of eighths is three `Note`s of `1/8` inside a `\tuplet 3/2 { }`.
`duration_token` therefore has no arithmetic to undo, and it **raises** on a
duration with no notehead. That raise is the contract enforced at the
boundary: a sounding triplet eighth is `1/12`, there is no twelfth note, and a
pipeline that ever stored sounding time would fail here rather than silently
engrave the wrong note value.

## Two conventions are reversed, and both bite silently

**Strings.** The IR indexes from 0 as the lowest; LilyPond numbers from 1 as
the highest. `lily_string_number` is the only place that mapping exists.

**Octaves.** Bass guitar is written an octave above its sound. Everything
emitted here — the notes *and* the `stringTunings` chord — is transposed up by
`_WRITTEN_OCTAVE` and read under `\clef "bass_8"`, which is the convention
LilyPond's own `bass-six-string-tuning` uses. The two must move together:
LilyPond derives each fret number from the note's pitch against the declared
tuning, so a transposition applied to one and not the other would put every
fret number twelve semitones out while the tablature still looked like music.

## The staff mode is a branch, not a flag (spec §10)

`TabStaff` suppresses stems and beams by default, assuming a notation staff
above supplies the rhythm. In `tab` mode there is no staff above, so the tab
staff stands alone: it asks for `\tabFullNotation`, keeps its fingerings, and
carries the tempo mark that the notation staff would otherwise hold.

## Instructional prose is cover-page only (spec §12, decision #10)

`Score.instruction` is read by `emit_book` and by nothing else. It never
reaches an exercise page, where it would compete with the notes.
"""

from dataclasses import dataclass
from fractions import Fraction
from typing import TYPE_CHECKING

from melete import theory, vocabulary

# The accepted staff modes are taken from `config` rather than restated here.
# §10's switch has to mean the same thing to the loader that validates it and
# to the emitter that branches on it, and two tuples that must agree are the
# drift decision #19 exists to prevent.
from melete.config import STAVES
from melete.score import Note, Tuplet

if TYPE_CHECKING:
    from collections.abc import Sequence

    from melete.score import Score, Voice

#: Declared in every emitted file. LilyPond warns loudly without one and
#: `convert-ly` reads it, so it is pinned to the oldest release melete targets
#: — Debian trixie's 2.24 series — rather than to whatever is installed.
LILYPOND_VERSION = "2.24.0"

#: Bass guitar sounds an octave below its notation. Notes and tunings are both
#: written up by this and read under `\clef "bass_8"`. See the module docstring.
_WRITTEN_OCTAVE = 12

#: LilyPond's unmarked octave: `c` is C3, `c'` is middle C. `pitch // 12` for
#: C3 is 4, so this is the octave number that needs no `'` or `,`.
_REFERENCE_OCTAVE = 4

#: Voice items per line of generated source. §12 keeps the `.ly` on disk for
#: inspection, and a hundred notes on one line is not inspectable.
_ITEMS_PER_LINE = 8

#: Written duration as a multiple of the undotted note it augments. A dot adds
#: half, a second dot adds a quarter; three dots are deliberately absent — see
#: `duration_token`.
_AUGMENTATIONS: tuple[tuple[int, Fraction], ...] = (
    (0, Fraction(1)),
    (1, Fraction(3, 2)),
    (2, Fraction(7, 4)),
)

#: The axes §12 prints as one musical phrase — "D Dorian", "D minor 7th" —
#: rather than as separate comma-separated items.
_TONAL_AXES = ("scale_type", "quality")

_PREAMBLE = "% Generated by melete. Edits here are overwritten by the next run."


def _lilypond_pitch_name(name: str) -> str:
    """`theory`'s pitch-class spelling in LilyPond's default note names.

    Derived rather than retyped: `theory` owns the spelling, so the cover page
    and the engraved notes cannot disagree about whether a pitch class is a
    D-flat or a C-sharp.
    """
    return name[0].lower() + name[1:].replace("b", "es").replace("#", "is")


_PITCH_NAMES: tuple[str, ...] = tuple(_lilypond_pitch_name(n) for n in theory.PITCH_CLASSES)


@dataclass(frozen=True)
class Cover:
    """The cover page's own content: the date and the instrument (spec §12).

    Everything else on the page — one entry per exercise, in plain language —
    is derived from the scores themselves, so the two cannot drift apart.
    """

    date: str
    instrument: str


# --------------------------------------------------------------------------
# The two units that are wrong silently
# --------------------------------------------------------------------------


def duration_token(written: Fraction) -> str:
    r"""The LilyPond duration for one **written** value: `1/4` is `"4"`.

    Dots are recovered by division rather than by table: `3/8` is `4.` and
    `7/16` is `4..`. A value that is not a power-of-two note with zero, one or
    two dots has no notehead and raises.

    The raise is the point. Sounding durations inside a tuplet are not
    representable — a triplet eighth is `1/12` — so this is where the
    written-duration contract of the `score` seam is enforced (decision #16).
    Three dots are excluded with the same intent: LilyPond can engrave one, but
    nothing upstream produces one, and widening the accepted set quietly is how
    an unwritable duration eventually reaches the page.
    """
    for dots, augmentation in _AUGMENTATIONS:
        base = written / augmentation
        if base.numerator == 1 and not base.denominator & (base.denominator - 1):
            return f"{base.denominator}" + "." * dots

    msg = (
        f"{written} is not a representable note value. Durations are the "
        f"written value (decision #16): a power-of-two note, optionally with "
        f"one or two dots. A sounding triplet eighth is 1/12 and there is no "
        f"twelfth note — store 1/8 inside a Tuplet and let the ratio scale it."
    )
    raise ValueError(msg)


def lily_string_number(index: int, string_count: int) -> int:
    """The LilyPond string number for an IR string index.

    **The two conventions are reversed.** The IR indexes strings from 0 as the
    *lowest* (spec §5); LilyPond numbers them from 1 as the *highest*. On a
    six-string bass, IR index 5 is LilyPond string 1 and IR index 0 is string
    6. The mapping is not the identity anywhere, and getting it wrong puts
    every fret number on the wrong line while the tablature still reads as
    music — which is why it is a named function with its own test rather than
    an expression inline.

    An index the instrument has no string for raises rather than wrapping: a
    negative index would address the tuning from the top and engrave plausible
    tablature for the wrong strings, exactly as §5 says of tunings.
    """
    if not 0 <= index < string_count:
        msg = (
            f"string index {index} is out of range for an instrument with "
            f"{string_count} strings: expected 0 to {string_count - 1}, "
            f"counting from the lowest string."
        )
        raise ValueError(msg)
    return string_count - index


# --------------------------------------------------------------------------
# Notes and voices
# --------------------------------------------------------------------------


def _quoted(text: str) -> str:
    """A LilyPond string literal. Backslash first, or it escapes the escapes."""
    escaped = text.replace("\\", r"\\").replace('"', r"\"")
    return f'"{escaped}"'


def _pitch_token(pitch: int) -> str:
    """An absolute pitch as a LilyPond note name with its octave marks.

    The argument is the **written** pitch, already transposed by the caller.
    """
    octave, pitch_class = divmod(pitch, 12)
    distance = octave - _REFERENCE_OCTAVE
    marks = "'" * distance if distance > 0 else "," * -distance
    return _PITCH_NAMES[pitch_class] + marks


def _note_token(note: Note, string_count: int) -> str:
    r"""One note: pitch, duration, string, fingering, accent — in that order.

    The string indication has to be there even in `notation` mode, because the
    same music expression feeds both staves; the notation staff omits the
    `StringNumber` grob instead of receiving different music.
    """
    token = _pitch_token(note.pitch + _WRITTEN_OCTAVE) + duration_token(note.duration)
    token += f"\\{lily_string_number(note.string, string_count)}"
    if note.finger is not None:
        token += f"-{note.finger}"
    if note.accent:
        token += "->"
    return token


def _voice_tokens(voice: Voice, string_count: int) -> list[str]:
    r"""One token per voice item; a tuplet is one item, braces and all.

    `Tuplet.ratio` maps straight onto `\tuplet 3/2 { ... }` with no arithmetic,
    which is exactly what the written-duration contract buys (decision #16).
    """
    tokens = []
    for item in voice:
        if isinstance(item, Tuplet):
            numerator, denominator = item.ratio
            inner = " ".join(_note_token(note, string_count) for note in item.notes)
            tokens.append(f"\\tuplet {numerator}/{denominator} {{ {inner} }}")
        else:
            tokens.append(_note_token(item, string_count))
    return tokens


def _music_lines(score: Score, indent: str) -> list[str]:
    r"""The shared music: accidental style, meter, the notes, the final bar.

    `\accidentalStyle forget` is here rather than on the notation staff so it
    is present in every staff mode: §10 and decision #9 make explicit
    accidentals a property of the exercise, not of one rendering of it. In a
    tab staff it is inert, which is the correct amount of effect.

    The final `\bar "|."` closes the short last measure §7 accepts. It is not
    padded with rests — a player would read rests as musical content.
    """
    beats, beat_value = score.time_signature
    lines = [
        f"{indent}\\accidentalStyle forget",
        f"{indent}\\time {beats}/{beat_value}",
    ]
    tokens = _voice_tokens(score.voice, len(score.instrument.tuning))
    for start in range(0, len(tokens), _ITEMS_PER_LINE):
        lines.append(indent + " ".join(tokens[start : start + _ITEMS_PER_LINE]))
    lines.append(f'{indent}\\bar "|."')
    return lines


def _tempo_line(score: Score, indent: str) -> str:
    """The metronome mark, in the beat unit the time signature names.

    §12 prints the tempo range on the cover page; this puts the same range over
    the exercise, which is the one annotation a player reads from the stand.
    """
    _, beat_value = score.time_signature
    slowest, fastest = score.tempo_range
    return f"{indent}\\tempo {beat_value} = {slowest} - {fastest}"


# --------------------------------------------------------------------------
# Staves
# --------------------------------------------------------------------------


def _notation_staff(score: Score, indent: str) -> list[str]:
    r"""The standard-notation staff, always the top staff when it is present.

    `\omit StringNumber` because the string indications on every note exist for
    the tab staff; printed here they would be circled numerals over music that
    already says where to play.
    """
    return [
        f"{indent}\\new Staff \\with {{",
        f"{indent}  \\omit StringNumber",
        f"{indent}}} {{",
        f'{indent}  \\clef "bass_8"',
        _tempo_line(score, f"{indent}  "),
        *_music_lines(score, f"{indent}  "),
        f"{indent}}}",
    ]


def _string_tuning(score: Score) -> str:
    """The instrument's tuning as a LilyPond chord, low string first.

    Written an octave up to match the notes, for the reason in the module
    docstring: LilyPond derives every fret number from pitch against this.
    """
    written = (_pitch_token(pitch + _WRITTEN_OCTAVE) for pitch in score.instrument.tuning)
    return f"\\stringTuning <{' '.join(written)}>"


def _tab_staff(score: Score, indent: str, *, alone: bool) -> list[str]:
    r"""The tablature staff. `alone` is the §10 branch, not a flag.

    With no notation staff above, three things follow from the same fact:
    `TabStaff` must be asked for stems and beams explicitly or the rhythm is
    unreadable, the fingerings have nowhere else to be printed, and the tempo
    mark has no other staff to sit over.
    """
    settings = [f"{indent}  stringTunings = {_string_tuning(score)}"]
    if not alone:
        settings.append(f"{indent}  \\omit Fingering")

    prelude = []
    if alone:
        prelude.append(f"{indent}  \\tabFullNotation")
        prelude.append(_tempo_line(score, f"{indent}  "))

    return [
        f"{indent}\\new TabStaff \\with {{",
        *settings,
        f"{indent}}} {{",
        *prelude,
        *_music_lines(score, f"{indent}  "),
        f"{indent}}}",
    ]


def _check_staves(staves: str) -> None:
    """Reject an unknown staff mode by name (§13: never a silent fallback)."""
    if staves not in STAVES:
        msg = f"unknown staff mode {staves!r}; accepted: {list(STAVES)}"
        raise ValueError(msg)


def _score_block(score: Score, staves: str, indent: str, *, piece: str | None) -> list[str]:
    r"""One `\score { }`: the staves §10 asks for, and nothing else.

    `piece` titles the score from inside a book, where a `\header` `title`
    belongs to the bookpart rather than to one exercise.
    """
    lines = [f"{indent}\\score {{"]
    if piece is not None:
        lines += [
            f"{indent}  \\header {{",
            f"{indent}    piece = {_quoted(piece)}",
            f"{indent}  }}",
        ]

    lines.append(f"{indent}  <<")
    inner = f"{indent}    "
    if staves in ("both", "notation"):
        lines += _notation_staff(score, inner)
    if staves in ("both", "tab"):
        lines += _tab_staff(score, inner, alone=staves == "tab")

    lines += [f"{indent}  >>", f"{indent}  \\layout {{ }}", f"{indent}}}"]
    return lines


# --------------------------------------------------------------------------
# The cover page (spec §12)
# --------------------------------------------------------------------------


def _pitch_class_name(value: object) -> str:
    """A `root` parameter as a note name. Never a fallback (§13)."""
    if not isinstance(value, int):
        msg = f"cover entry: root must be a pitch-class integer, got {value!r}"
        raise TypeError(msg)
    if not 0 <= value < len(theory.PITCH_CLASSES):
        msg = (
            f"cover entry: root {value} is outside 0-11. Roots are pitch "
            f"classes, not absolute pitches."
        )
        raise ValueError(msg)
    return theory.PITCH_CLASSES[value]


def _tonal_phrase(params: dict[str, object]) -> str:
    """The tonal axes as §12's single phrase: "D Dorian", or "D minor 7th".

    Emitted ahead of the rest regardless of the order `params` happens to
    carry, because "D, Dorian" is not what a player reads.
    """
    words = []
    if "root" in params:
        words.append(_pitch_class_name(params["root"]))
    for axis in _TONAL_AXES:
        if axis in params:
            words.append(vocabulary.display(axis, str(params[axis])))
    return " ".join(words)


def _phrase(axis: str, value: object) -> str:
    """One parameter in plain language.

    Axes in the registry are rendered through it, and an identifier it does not
    know raises there (§13, decision #19). The rest are the range axes
    `vocabulary` deliberately does not enumerate — fret numbers, octave counts,
    string sets — which are printed as themselves rather than dropped.
    """
    if axis in vocabulary.AXES:
        return vocabulary.display(axis, str(value))
    return f"{axis.replace('_', ' ')} {value}"


def _cover_entry(number: int, score: Score) -> list[str]:
    """One numbered cover entry, plus the focus cue when the family gave one."""
    phrases = []
    tonal = _tonal_phrase(score.params)
    if tonal:
        phrases.append(tonal)
    phrases += [
        _phrase(axis, value)
        for axis, value in score.params.items()
        if axis != "root" and axis not in _TONAL_AXES
    ]
    slowest, fastest = score.tempo_range
    phrases.append(f"{slowest}-{fastest} bpm")

    lines = [f"    \\markup \\wordwrap-string #{_quoted(f'{number}. ' + ', '.join(phrases))}"]
    if score.instruction:
        lines.append(f"    \\markup \\italic \\wordwrap-string #{_quoted(score.instruction)}")
    lines.append("    \\markup \\vspace #1")
    return lines


def _cover_bookpart(scores: Sequence[Score], cover: Cover) -> list[str]:
    r"""The cover page as a markup bookpart in the same book (spec §12).

    A bookpart rather than a separate document so the day's output stays one
    PDF from one render call, with no text-to-PDF dependency anywhere.
    """
    lines = [
        "  \\bookpart {",
        "    \\markup \\vspace #3",
        f"    \\markup \\fill-line {{ \\fontsize #6 \\bold {_quoted('Practice session')} }}",
        "    \\markup \\vspace #1",
        f"    \\markup \\fill-line {{ {_quoted(f'{cover.date} — {cover.instrument}')} }}",
        "    \\markup \\vspace #3",
    ]
    for number, score in enumerate(scores, start=1):
        lines += _cover_entry(number, score)
    lines.append("  }")
    return lines


# --------------------------------------------------------------------------
# The two entry points
# --------------------------------------------------------------------------


def emit_score(score: Score, staves: str = "both") -> str:
    """One exercise as a standalone LilyPond document.

    §12 keeps the generated source per exercise as well as for the book, so
    this is a complete file rather than a fragment. `score.instruction` is not
    read here and never appears in the result.
    """
    _check_staves(staves)
    lines = [
        _PREAMBLE,
        f'\\version "{LILYPOND_VERSION}"',
        "",
        "\\header {",
        f"  title = {_quoted(score.title)}",
        "  tagline = ##f",
        "}",
        "",
        *_score_block(score, staves, "", piece=None),
    ]
    return "\n".join(lines) + "\n"


def emit_book(scores: Sequence[Score], cover: Cover, staves: str = "both") -> str:
    """A day's session as one LilyPond book: the cover page, then the exercises.

    One document from one render call (§12, decision #11). The cover carries
    the instructional prose; the exercise pages carry a title and the tempo and
    nothing else (decision #10).
    """
    _check_staves(staves)
    if not scores:
        msg = "a book needs at least one exercise; a cover page with no exercises is not a session"
        raise ValueError(msg)

    lines = [
        _PREAMBLE,
        f'\\version "{LILYPOND_VERSION}"',
        "",
        "\\header {",
        "  tagline = ##f",
        "}",
        "",
        "\\book {",
        *_cover_bookpart(scores, cover),
        "",
        "  \\bookpart {",
    ]
    for number, score in enumerate(scores, start=1):
        if number > 1:
            lines.append("")
        lines += _score_block(score, staves, "    ", piece=f"{number}. {score.title}")
    lines += ["  }", "}"]
    return "\n".join(lines) + "\n"
